displayName: Metro Rapid Repair
schemaName: cdv_metrorepairs
accessControlPolicy: GroupMembership
authenticationMode: None
authenticationTrigger: AsNeeded
configuration:
  settings:
    AnonymousAccessDisabled: true
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cdv_metrorepairs.gpt.default

  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-10-02T21:50:47.0000000Z
template: default-2.1.0
language: 1033