displayName: Riverside Auto Care
schemaName: cdv_riversiderepairs
accessControlPolicy: GroupMembership
authenticationMode: None
authenticationTrigger: AsNeeded
configuration:
  settings:
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cdv_riversiderepairs.gpt.default

  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-09-30T21:28:57.0000000Z
template: default-2.1.0
language: 1033