displayName: Caldova Repair Coordinator
schemaName: cdv_repaircoordinator
accessControlPolicy: GroupMembership
authenticationMode: None
authenticationTrigger: AsNeeded
configuration:
  settings:
    AnonymousAccessDisabled: true
    GenerativeActionsEnabled: true

  isAgentConnectable: true
  gPTSettings:
    defaultSchemaName: cdv_repaircoordinator.gpt.default

  aISettings:
    useModelKnowledge: true
    isFileAnalysisEnabled: true
    isSemanticSearchEnabled: true
    optInUseLatestModels: false

  recognizer:
    kind: GenerativeAIRecognizer

publishedOn: 2026-09-30T23:31:01.0000000Z
template: default-2.1.0
language: 1033